version: 2

models:
  # Staging Layer - Ibis model with Hamilton DAG integration
  - name: stg_pv_consolidated
    description: "Consolidated staging table of processed PV installation geometries from all DOI datasets"
    columns:
      - name: dataset_name
        description: "Unique identifier for the source dataset"
        tests:
          - not_null
      - name: source_file
        description: "Source file or DOI reference for traceability"
        tests:
          - not_null
      - name: geometry
        description: "Geometry in Well-Known Text format (from DuckLake geometry_wkt)"
        tests:
          - not_null
      - name: centroid_lon
        description: "Longitude of the geometry centroid"
      - name: centroid_lat
        description: "Latitude of the geometry centroid"

  # Note: Prepared layer models are disabled (enabled=false) until dependencies are implemented
  # Schema definitions removed to avoid compilation errors - will be re-added when models are enabled

  # Curated Layer - Draft models for future development
  - name: curated_pv_dataset_summary_draft
    description: "DRAFT: Basic summary of PV datasets - to be refined later"
    columns:
      - name: dataset_name
        description: "Unique identifier for the dataset"
        tests:
          - not_null
      - name: installation_count
        description: "Number of PV installations in the dataset"
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      - name: status
        description: "Model development status"
        tests:
          - accepted_values:
              values: ['DRAFT - TO BE REFINED']
