version: 2

models:
  # Raw Layer - Schema definitions for all raw models
  - name: raw_usa_cali_usgs_pv_2016
    description: "Raw USA California USGS PV 2016 dataset"
    columns:
      # Actual columns from the dataset (all as varchar to prevent casting errors)
      - name: polygon_id
        data_type: varchar
      - name: centroid_latitude
        data_type: varchar
      - name: centroid_longitude
        data_type: varchar
      - name: centroid_latitude_pixels
        data_type: varchar
      - name: centroid_longitude_pixels
        data_type: varchar
      - name: city
        data_type: varchar
      - name: area_pixels
        data_type: varchar
      - name: area_meters
        data_type: varchar
      - name: image_name
        data_type: varchar
      - name: nw_corner_of_image_latitude
        data_type: varchar
      - name: nw_corner_of_image_longitude
        data_type: varchar
      - name: se_corner_of_image_latitude
        data_type: varchar
      - name: se_corner_of_image_longitude
        data_type: varchar
      - name: datum
        data_type: varchar
      - name: projection_zone
        data_type: varchar
      - name: resolution
        data_type: varchar
      - name: jaccard_index
        data_type: varchar
      - name: polygon_vertices_pixels
        data_type: varchar
      - name: dataset_name
        data_type: varchar
      - name: source_file
        data_type: varchar
      - name: bbox
        data_type: varchar
      - name: geometry_wkt
        data_type: varchar
      - name: geometry_wkb
        data_type: blob
      - name: dataset_name_1
        data_type: varchar
      - name: doi
        data_type: varchar
      - name: repo
        data_type: varchar
      - name: paper_doi
        data_type: varchar
      - name: paper_title
        data_type: varchar
      - name: dbt_loaded_at
        data_type: timestamp

  - name: raw_uk_crowdsourced_pv_2020
    description: "Raw UK Crowdsourced PV 2020 dataset"
    columns:
      # Actual columns from the dataset (all as varchar to prevent casting errors)
      - name: osm_id
        data_type: varchar
      - name: osm_name
        data_type: varchar
      - name: osm_objtype
        data_type: varchar
      - name: repd_id
        data_type: varchar
      - name: repd_site_name
        data_type: varchar
      - name: capacity_repd_MWp
        data_type: varchar
      - name: capacity_osm_MWp
        data_type: varchar
      - name: area_sqm
        data_type: varchar
      - name: located
        data_type: varchar
      - name: orientation
        data_type: varchar
      - name: osm_power_type
        data_type: varchar
      - name: osm_tag_start_date
        data_type: varchar
      - name: num_modules
        data_type: varchar
      - name: repd_status
        data_type: varchar
      - name: repd_operational_date
        data_type: varchar
      - name: old_repd_id
        data_type: varchar
      - name: osm_cluster_id
        data_type: varchar
      - name: repd_cluster_id
        data_type: varchar
      - name: source_capacity
        data_type: varchar
      - name: source_obj
        data_type: varchar
      - name: match_rule
        data_type: varchar
      - name: dataset_name
        data_type: varchar
      - name: source_file
        data_type: varchar
      - name: bbox
        data_type: varchar
      - name: geometry_wkt
        data_type: varchar
      - name: geometry_wkb
        data_type: blob
      - name: dataset_name_1
        data_type: varchar
      - name: doi
        data_type: varchar
      - name: repo
        data_type: varchar
      - name: paper_doi
        data_type: varchar
      - name: paper_title
        data_type: varchar
      - name: dbt_loaded_at
        data_type: timestamp

  - name: raw_chn_med_res_pv_2024
    description: "Raw China Medium Resolution PV 2024 dataset"
    columns:
      # Original columns from source data (all as varchar to prevent casting errors)
      - name: id
        data_type: varchar
      - name: province
        data_type: varchar
      - name: city
        data_type: varchar
      - name: capacity_mw
        data_type: varchar
      - name: area_m2
        data_type: varchar
      - name: install_date
        data_type: varchar
      # New columns added by raw model
      - name: geometry_wkt
        data_type: varchar
      - name: geometry_wkb
        data_type: blob
      - name: dataset_name
        data_type: varchar
      - name: doi
        data_type: varchar
      - name: repo
        data_type: varchar
      - name: paper_doi
        data_type: varchar
      - name: paper_title
        data_type: varchar
      - name: dbt_loaded_at
        data_type: timestamp

  - name: raw_global_pv_inventory_sent2_spot_2021
    description: "Raw Global PV Inventory Sentinel-2 SPOT 2021 dataset"
    columns:
      - name: geometry_wkt
        data_type: varchar
      - name: geometry_wkb
        data_type: blob
      - name: dataset_name
        data_type: varchar
      - name: doi
        data_type: varchar
      - name: repo
        data_type: varchar
      - name: paper_doi
        data_type: varchar
      - name: paper_title
        data_type: varchar
      - name: dbt_loaded_at
        data_type: timestamp

  - name: raw_ind_pv_solar_farms_2022
    description: "Raw India PV Solar Farms 2022 dataset"
    columns:
      - name: geometry_wkt
        data_type: varchar
      - name: geometry_wkb
        data_type: blob
      - name: dataset_name
        data_type: varchar
      - name: doi
        data_type: varchar
      - name: repo
        data_type: varchar
      - name: paper_doi
        data_type: varchar
      - name: paper_title
        data_type: varchar
      - name: dbt_loaded_at
        data_type: timestamp

  - name: raw_global_harmonized_large_solar_farms_2020
    description: "Raw Global Harmonized Large Solar Farms 2020 dataset"
    columns:
      # Original columns from source data (all as varchar to prevent casting errors)
      - name: id
        data_type: varchar
      - name: country
        data_type: varchar
      - name: state
        data_type: varchar
      - name: city
        data_type: varchar
      - name: capacity_mw
        data_type: varchar
      - name: area_m2
        data_type: varchar
      - name: install_date
        data_type: varchar
      # New columns added by raw model
      - name: geometry_wkt
        data_type: varchar
      - name: geometry_wkb
        data_type: blob
      - name: dataset_name
        data_type: varchar
      - name: doi
        data_type: varchar
      - name: repo
        data_type: varchar
      - name: paper_doi
        data_type: varchar
      - name: paper_title
        data_type: varchar
      - name: dbt_loaded_at
        data_type: timestamp

  - name: raw_ind_pv_solar_farms_2022
    description: "Raw India PV Solar Farms 2022 dataset"
    columns:
      # Actual columns from the dataset (all as varchar to prevent casting errors)
      - name: State
        data_type: varchar
      - name: Area
        data_type: varchar
      - name: Latitude
        data_type: varchar
      - name: Longitude
        data_type: varchar
      - name: fid
        data_type: varchar
      - name: dataset_name
        data_type: varchar
      - name: source_file
        data_type: varchar
      - name: bbox
        data_type: varchar
      - name: geometry_wkt
        data_type: varchar
      - name: geometry_wkb
        data_type: blob
      - name: dataset_name_1
        data_type: varchar
      - name: doi
        data_type: varchar
      - name: repo
        data_type: varchar
      - name: paper_doi
        data_type: varchar
      - name: paper_title
        data_type: varchar
      - name: dbt_loaded_at
        data_type: timestamp

  - name: raw_global_pv_inventory_sent2_spot_2021
    description: "Raw Global PV Inventory Sentinel-2 SPOT 2021 dataset"
    columns:
      # Original columns from source data (all as varchar to prevent casting errors)
      - name: id
        data_type: varchar
      - name: country
        data_type: varchar
      - name: region
        data_type: varchar
      - name: capacity_mw
        data_type: varchar
      - name: area_m2
        data_type: varchar
      - name: install_date
        data_type: varchar
      # New columns added by raw model
      - name: geometry_wkt
        data_type: varchar
      - name: geometry_wkb
        data_type: blob
      - name: dataset_name
        data_type: varchar
      - name: doi
        data_type: varchar
      - name: repo
        data_type: varchar
      - name: paper_doi
        data_type: varchar
      - name: paper_title
        data_type: varchar
      - name: dbt_loaded_at
        data_type: timestamp
  # Staging Layer - Ibis model with Hamilton DAG integration
  - name: stg_pv_consolidated
    description: "Consolidated staging table of processed PV installation geometries from all DOI datasets"
    columns:
      - name: dataset_name
        description: "Unique identifier for the source dataset"
        data_type: varchar
        tests:
          - not_null
      - name: geometry
        description: "Geometry in Well-Known Text format (from DuckLake geometry_wkt)"
        data_type: varchar
        tests:
          - not_null
      - name: centroid_lon
        description: "Longitude of the geometry centroid"
        data_type: double
      - name: centroid_lat
        description: "Latitude of the geometry centroid"
        data_type: double
      - name: area_m2
        description: "Installation area in square meters"
        data_type: double
      - name: processed_at
        description: "Hamilton processing timestamp"
        data_type: timestamp
      - name: h3_index_12
        description: "H3 spatial index at resolution 12 for efficient spatial operations"
        data_type: uint64
      - name: unified_id
        description: "Standardized unique identifier across datasets"
        data_type: varchar
      - name: source_area_m2
        description: "Original area measurement from source dataset"
        data_type: double
      - name: capacity_mw
        description: "Installation capacity in megawatts"
        data_type: double
      - name: install_date
        description: "Installation date"
        data_type: varchar

  # Individual staging models - need schema definitions to include H3 column
  - name: stg_usa_cali_usgs_pv_2016
    description: "Standardized USA California USGS PV 2016 dataset"
    columns:
      - name: dataset_name
        data_type: varchar
      - name: geometry
        data_type: varchar
      - name: area_m2
        data_type: double
      - name: centroid_lat
        data_type: double
      - name: centroid_lon
        data_type: double
      - name: processed_at
        data_type: timestamp
      - name: h3_index_12
        data_type: uint64
      - name: unified_id
        data_type: varchar
      - name: source_area_m2
        data_type: double
      - name: capacity_mw
        data_type: double
      - name: install_date
        data_type: varchar

  - name: stg_uk_crowdsourced_pv_2020
    description: "Standardized UK Crowdsourced PV 2020 dataset"
    columns:
      - name: dataset_name
        data_type: varchar
      - name: geometry
        data_type: varchar
      - name: area_m2
        data_type: double
      - name: centroid_lat
        data_type: double
      - name: centroid_lon
        data_type: double
      - name: processed_at
        data_type: timestamp
      - name: h3_index_12
        data_type: uint64
      - name: unified_id
        data_type: varchar
      - name: source_area_m2
        data_type: double
      - name: capacity_mw
        data_type: double
      - name: install_date
        data_type: varchar

  - name: stg_chn_med_res_pv_2024
    description: "Standardized China Medium Resolution PV 2024 dataset"
    columns:
      - name: dataset_name
        data_type: varchar
      - name: geometry
        data_type: varchar
      - name: area_m2
        data_type: double
      - name: centroid_lat
        data_type: double
      - name: centroid_lon
        data_type: double
      - name: processed_at
        data_type: timestamp
      - name: h3_index_12
        data_type: uint64
      - name: unified_id
        data_type: varchar
      - name: source_area_m2
        data_type: double
      - name: capacity_mw
        data_type: double
      - name: install_date
        data_type: varchar

  - name: stg_global_pv_inventory_sent2_spot_2021
    description: "Standardized Global PV Inventory Sentinel-2 SPOT 2021 dataset"
    columns:
      - name: dataset_name
        data_type: varchar
      - name: geometry
        data_type: varchar
      - name: area_m2
        data_type: double
      - name: centroid_lat
        data_type: double
      - name: centroid_lon
        data_type: double
      - name: processed_at
        data_type: varchar
      - name: h3_index_12
        data_type: uint64
      - name: unified_id
        data_type: varchar
      - name: source_area_m2
        data_type: double
      - name: capacity_mw
        data_type: double
      - name: install_date
        data_type: varchar

  - name: stg_ind_pv_solar_farms_2022
    description: "Standardized India PV Solar Farms 2022 dataset"
    columns:
      - name: dataset_name
        data_type: varchar
      - name: geometry
        data_type: varchar
      - name: area_m2
        data_type: double
      - name: centroid_lat
        data_type: double
      - name: centroid_lon
        data_type: double
      - name: processed_at
        data_type: timestamp
      - name: h3_index_12
        data_type: uint64
      - name: unified_id
        data_type: varchar
      - name: source_area_m2
        data_type: double
      - name: capacity_mw
        data_type: double
      - name: install_date
        data_type: varchar

  - name: stg_global_harmonized_large_solar_farms_2020
    description: "Standardized Global Harmonized Large Solar Farms 2020 dataset"
    columns:
      - name: dataset_name
        data_type: varchar
      - name: geometry
        data_type: varchar
      - name: area_m2
        data_type: double
      - name: centroid_lat
        data_type: double
      - name: centroid_lon
        data_type: double
      - name: processed_at
        data_type: varchar
      - name: h3_index_12
        data_type: uint64
      - name: unified_id
        data_type: varchar
      - name: source_area_m2
        data_type: double
      - name: capacity_mw
        data_type: double
      - name: install_date
        data_type: varchar

  # Note: Prepared layer models are disabled (enabled=false) until dependencies are implemented
  # Schema definitions removed to avoid compilation errors - will be re-added when models are enabled
