version: 2

sources:
  # DOI PV Raw Data - External GeoParquet files (for cloud deployment)
  - name: doi_pv_geoparquet
    description: "Raw DOI PV datasets from GeoParquet exports - for cloud deployment when files are in S3/R2"
    config:
      external_location: "{{ env_var('GPQ_EXPORT_PATH', env_var('REPO_ROOT') ~ '/db/geoparquet') }}"
    tables:
      - name: doi_uk_crowdsourced_pv_2020
        description: "UK Crowdsourced PV 2020 GeoParquet export"
        config:
          external_location: "{{ env_var('GPQ_EXPORT_PATH', env_var('REPO_ROOT') ~ '/db/geoparquet') }}/doi_uk_crowdsourced_pv_2020.parquet"
      - name: doi_chn_med_res_pv_2024
        description: "China Medium Resolution PV 2024 GeoParquet export"
        config:
          external_location: "{{ env_var('GPQ_EXPORT_PATH', env_var('REPO_ROOT') ~ '/db/geoparquet') }}/doi_chn_med_res_pv_2024.parquet"
      - name: doi_usa_cali_usgs_pv_2016
        description: "USA California USGS PV 2016 GeoParquet export"
        config:
          external_location: "{{ env_var('GPQ_EXPORT_PATH', env_var('REPO_ROOT') ~ '/db/geoparquet') }}/doi_usa_cali_usgs_pv_2016.parquet"
      - name: doi_ind_pv_solar_farms_2022
        description: "India PV Solar Farms 2022 GeoParquet export"
        config:
          external_location: "{{ env_var('GPQ_EXPORT_PATH', env_var('REPO_ROOT') ~ '/db/geoparquet') }}/doi_ind_pv_solar_farms_2022.parquet"
      - name: doi_global_pv_inventory_sent2_spot_2021
        description: "Global PV Inventory Sentinel-2 SPOT 2021 GeoParquet export"
        config:
          external_location: "{{ env_var('GPQ_EXPORT_PATH', env_var('REPO_ROOT') ~ '/db/geoparquet') }}/doi_global_pv_inventory_sent2_spot_2021.parquet"
      - name: doi_global_harmonized_large_solar_farms_2020
        description: "Global Harmonized Large Solar Farms 2020 GeoParquet export"
        config:
          external_location: "{{ env_var('GPQ_EXPORT_PATH', env_var('REPO_ROOT') ~ '/db/geoparquet') }}/doi_global_harmonized_large_solar_farms_2020.parquet"

  # DOI PV Raw Data - Database tables (for staging consolidation reference)
  - name: doi_pv_raw
    description: "Raw DOI PV datasets - individual tables per dataset from Hamilton DOI pipeline"
    database: eo_pv_data
    schema: main  # Hamilton creates tables in main schema
    config:
      freshness:
        warn_after: {count: 24, period: hour}
        error_after: {count: 48, period: hour}
      loaded_at_field: processed_at
    tables:
      # Individual dataset tables created by Hamilton with pattern: doi_{dataset_name}
      - name: doi_uk_crowdsourced_pv_2020
        description: "UK Crowdsourced PV 2020 dataset - Building-integrated PV installations with installation dates"
        columns:
          - name: dataset_name
            description: "Source dataset identifier"
            tests:
              - not_null
              - accepted_values:
                  values: ['uk_crowdsourced_pv_2020']
          - name: geometry
            description: "Geometry column (DuckDB spatial type)"
            tests:
              - not_null
          - name: area_m2
            description: "Installation area in square meters"
          - name: centroid_lon
            description: "Centroid longitude"
            tests:
              - dbt_utils.accepted_range:
                  min_value: -180
                  max_value: 180
          - name: centroid_lat
            description: "Centroid latitude"
            tests:
              - dbt_utils.accepted_range:
                  min_value: -90
                  max_value: 90
          - name: installation_date
            description: "Installation date (ground-truth value)"
          - name: capacity_mw
            description: "Capacity in megawatts (if available)"
          - name: processed_at
            description: "Hamilton processing timestamp"
            tests:
              - not_null

      - name: doi_chn_med_res_pv_2024
        description: "China Medium Resolution PV 2024 dataset - Utility-scale solar installations with capacity data"
        columns:
          - name: dataset_name
            description: "Source dataset identifier"
            tests:
              - not_null
              - accepted_values:
                  values: ['chn_med_res_pv_2024']
          - name: geometry
            description: "Geometry column (DuckDB spatial type)"
            tests:
              - not_null
          - name: area_m2
            description: "Installation area in square meters"
          - name: centroid_lon
            description: "Centroid longitude"
          - name: centroid_lat
            description: "Centroid latitude"
          - name: capacity_mw
            description: "Capacity in megawatts (ground-truth value)"
          - name: installation_type
            description: "Type of installation"
          - name: processed_at
            description: "Hamilton processing timestamp"
            tests:
              - not_null

      - name: doi_usa_cali_usgs_pv_2016
        description: "USA California USGS PV 2016 dataset - Residential/commercial PV with precise area estimates"
        columns:
          - name: dataset_name
            description: "Source dataset identifier"
            tests:
              - not_null
              - accepted_values:
                  values: ['usa_cali_usgs_pv_2016']
          - name: geometry
            description: "Geometry column (DuckDB spatial type)"
            tests:
              - not_null
          - name: area_m2
            description: "Installation area in square meters (precise estimate)"
          - name: centroid_lon
            description: "Centroid longitude"
          - name: centroid_lat
            description: "Centroid latitude"
          - name: building_type
            description: "Type of building (residential, commercial, etc.)"
          - name: processed_at
            description: "Hamilton processing timestamp"
            tests:
              - not_null

      - name: doi_ind_pv_solar_farms_2022
        description: "India PV Solar Farms 2022 dataset - Global PV installations"
        columns:
          - name: dataset_name
            description: "Source dataset identifier"
            tests:
              - not_null
              - accepted_values:
                  values: ['ind_pv_solar_farms_2022']
          - name: geometry
            description: "Geometry column (DuckDB spatial type)"
            tests:
              - not_null
          - name: area_m2
            description: "Installation area in square meters"
          - name: centroid_lon
            description: "Centroid longitude"
          - name: centroid_lat
            description: "Centroid latitude"
          - name: processed_at
            description: "Hamilton processing timestamp"
            tests:
              - not_null

      - name: doi_global_pv_inventory_sent2_spot_2021
        description: "Global PV Inventory Sentinel-2 SPOT 2021 dataset - Rooftop solar installations with building context"
        columns:
          - name: dataset_name
            description: "Source dataset identifier"
            tests:
              - not_null
              - accepted_values:
                  values: ['global_pv_inventory_sent2_spot_2021']
          - name: geometry
            description: "Geometry column (DuckDB spatial type)"
            tests:
              - not_null
          - name: area_m2
            description: "Installation area in square meters"
          - name: centroid_lon
            description: "Centroid longitude"
          - name: centroid_lat
            description: "Centroid latitude"
          - name: building_type
            description: "Type of building"
          - name: roof_orientation
            description: "Roof orientation (if available)"
          - name: processed_at
            description: "Hamilton processing timestamp"
            tests:
              - not_null

  # Hamilton Staging Output - Consolidated and standardized data
  - name: hamilton_staging
    description: "Staging tables and views created by Hamilton consolidation pipeline"
    database: eo_pv_data
    schema: main
    config:
      freshness:
        warn_after: {count: 6, period: hour}
        error_after: {count: 12, period: hour}
    tables:
      # Consolidated view that unions all individual staging tables
      - name: stg_pv_consolidated
        description: "Consolidated view of all PV datasets with standardized schema (created by Hamilton)"
        columns:
          - name: dataset_name
            description: "Source dataset identifier"
            tests:
              - not_null
          - name: source_file
            description: "Original source file name"
          - name: geometry
            description: "Geometry column (DuckDB spatial type)"
            tests:
              - not_null
          - name: centroid_lon
            description: "Centroid longitude"
            tests:
              - dbt_utils.accepted_range:
                  min_value: -180
                  max_value: 180
          - name: centroid_lat
            description: "Centroid latitude"
            tests:
              - dbt_utils.accepted_range:
                  min_value: -90
                  max_value: 90
          - name: area_m2
            description: "Installation area in square meters"
            tests:
              - dbt_utils.accepted_range:
                  min_value: 0
                  max_value: 1000000
          - name: processed_at
            description: "Hamilton processing timestamp"
            tests:
              - not_null
          - name: unified_id
            description: "Unified identifier across datasets"
          - name: source_area_m2
            description: "Original area from source data"
          - name: capacity_mw
            description: "Capacity in megawatts (if available)"
          - name: install_date
            description: "Installation date (if available)"

      # Individual staging tables (examples - Hamilton creates one per dataset)
      - name: stg_uk_crowdsourced_pv_2020
        description: "Standardized UK Crowdsourced PV 2020 dataset"
        columns:
          - name: dataset_name
            description: "Source dataset identifier"
            tests:
              - not_null
              - accepted_values:
                  values: ['uk_crowdsourced_pv_2020']
          - name: geometry
            description: "Geometry column (DuckDB spatial type)"
            tests:
              - not_null
          - name: area_m2
            description: "Installation area in square meters"
          - name: centroid_lon
            description: "Centroid longitude"
          - name: centroid_lat
            description: "Centroid latitude"
          - name: processed_at
            description: "Hamilton processing timestamp"
            tests:
              - not_null

      - name: doi_global_harmonized_large_solar_farms_2020
        description: "Global Harmonized Large Solar Farms 2020 dataset - Mixed PV types with installation metadata"
        columns:
          - name: dataset_name
            description: "Source dataset identifier"
            tests:
              - not_null
              - accepted_values:
                  values: ['global_harmonized_large_solar_farms_2020']
          - name: geometry
            description: "Geometry column (DuckDB spatial type)"
            tests:
              - not_null
          - name: area_m2
            description: "Installation area in square meters"
          - name: centroid_lon
            description: "Centroid longitude"
          - name: centroid_lat
            description: "Centroid latitude"
          - name: installation_type
            description: "Type of installation (utility, distributed, etc.)"
          - name: installation_date
            description: "Installation date (if available)"
          - name: processed_at
            description: "Hamilton processing timestamp"
            tests:
              - not_null
