version: 2

sources:
  # DOI PV Raw Data - External GeoParquet files (dynamic path based on target)
  - name: doi_pv_geoparquet
    description: "Raw DOI PV datasets from GeoParquet exports - local files for dev, R2 bucket for prod"
    config:
      # DEV: /local/path/to/geoparquet/files
      # PROD: s3://bucket/geoparquet/files
      external_location: "{% if target.name == 'prod' %}{{ env_var('GEOPARQUET_SOURCE_PATH') }}{% else %}{{ env_var('GEOPARQUET_SOURCE_PATH') }}{% endif %}"
    tables:
      - name: doi_uk_crowdsourced_pv_2020
        description: "UK Crowdsourced PV 2020 GeoParquet export"
        config:
          external_location: "{% if target.name == 'prod' %}{{ env_var('GEOPARQUET_SOURCE_PATH') }}{% else %}{{ env_var('GEOPARQUET_SOURCE_PATH') }}{% endif %}/doi_uk_crowdsourced_pv_2020.parquet"
      - name: doi_chn_med_res_pv_2024
        description: "China Medium Resolution PV 2024 GeoParquet export"
        config:
          external_location: "{% if target.name == 'prod' %}{{ env_var('GEOPARQUET_SOURCE_PATH') }}{% else %}{{ env_var('GEOPARQUET_SOURCE_PATH') }}{% endif %}/doi_chn_med_res_pv_2024.parquet"
      - name: doi_usa_cali_usgs_pv_2016
        description: "USA California USGS PV 2016 GeoParquet export"
        config:
          external_location: "{% if target.name == 'prod' %}{{ env_var('GEOPARQUET_SOURCE_PATH') }}{% else %}{{ env_var('GEOPARQUET_SOURCE_PATH') }}{% endif %}/doi_usa_cali_usgs_pv_2016.parquet"
      - name: doi_ind_pv_solar_farms_2022
        description: "India PV Solar Farms 2022 GeoParquet export"
        config:
          external_location: "{% if target.name == 'prod' %}{{ env_var('GEOPARQUET_SOURCE_PATH') }}{% else %}{{ env_var('GEOPARQUET_SOURCE_PATH') }}{% endif %}/doi_ind_pv_solar_farms_2022.parquet"
      - name: doi_global_pv_inventory_sent2_spot_2021
        description: "Global PV Inventory Sentinel-2 SPOT 2021 GeoParquet export"
        config:
          external_location: "{% if target.name == 'prod' %}{{ env_var('GEOPARQUET_SOURCE_PATH') }}{% else %}{{ env_var('GEOPARQUET_SOURCE_PATH') }}{% endif %}/doi_global_pv_inventory_sent2_spot_2021.parquet"
      - name: doi_global_harmonized_large_solar_farms_2020
        description: "Global Harmonized Large Solar Farms 2020 GeoParquet export"
        config:
          external_location: "{% if target.name == 'prod' %}{{ env_var('GEOPARQUET_SOURCE_PATH') }}{% else %}{{ env_var('GEOPARQUET_SOURCE_PATH') }}{% endif %}/doi_global_harmonized_large_solar_farms_2020.parquet"

  # DOI PV Raw Data - Database tables (for staging consolidation reference)
  - name: doi_pv_raw
    description: "Raw DOI PV datasets - individual tables per dataset from Hamilton DOI pipeline"
    database: eo_pv_lakehouse  # DuckLake catalog attached in on-run-start
    schema: main  # Hamilton creates tables in main schema
    loaded_at_field: processed_at
    tables:
      # Individual dataset tables created by Hamilton with pattern: raw_{dataset_name}
      - name: raw_uk_crowdsourced_pv_2020
        description: "UK Crowdsourced PV 2020 dataset - Raw data with original column names"
        columns:
          - name: dataset_name
            description: "Source dataset identifier (added by Hamilton)"
            tests:
              - not_null
          - name: geometry
            description: "Geometry column (WKT strings in DuckLake)"
            tests:
              - not_null
          - name: source_file
            description: "Original source file name"

      - name: raw_chn_med_res_pv_2024
        description: "China Medium Resolution PV 2024 dataset - Raw data with original column names"
        columns:
          - name: dataset_name
            description: "Source dataset identifier (added by Hamilton)"
            tests:
              - not_null
          - name: geometry
            description: "Geometry column (WKT strings in DuckLake)"
            tests:
              - not_null
          - name: source_file
            description: "Original source file name"

      - name: raw_usa_cali_usgs_pv_2016
        description: "USA California USGS PV 2016 dataset - Raw data with original column names"
        columns:
          - name: dataset_name
            description: "Source dataset identifier (added by Hamilton)"
            tests:
              - not_null
          - name: geometry
            description: "Geometry column (WKT strings in DuckLake)"
            tests:
              - not_null
          - name: source_file
            description: "Original source file name"

      - name: raw_ind_pv_solar_farms_2022
        description: "India PV Solar Farms 2022 dataset - Raw data with original column names"
        columns:
          - name: dataset_name
            description: "Source dataset identifier (added by Hamilton)"
            tests:
              - not_null
          - name: geometry
            description: "Geometry column (WKT strings in DuckLake)"
            tests:
              - not_null
          - name: source_file
            description: "Original source file name"

      - name: raw_global_pv_inventory_sent2_spot_2021
        description: "Global PV Inventory Sentinel-2 SPOT 2021 dataset - Raw data with original column names"
        columns:
          - name: dataset_name
            description: "Source dataset identifier (added by Hamilton)"
            tests:
              - not_null
          - name: geometry
            description: "Geometry column (WKT strings in DuckLake)"
            tests:
              - not_null
          - name: source_file
            description: "Original source file name"

      - name: raw_global_harmonized_large_solar_farms_2020
        description: "Global Harmonized Large Solar Farms 2020 dataset - Raw data with original column names"
        columns:
          - name: dataset_name
            description: "Source dataset identifier (added by Hamilton)"
            tests:
              - not_null
          - name: geometry
            description: "Geometry column (WKT strings in DuckLake)"
            tests:
              - not_null
          - name: source_file
            description: "Original source file name"

  # Hamilton Staging Output - Consolidated and standardized data
  - name: hamilton_staging
    description: "Staging tables and views created by Hamilton consolidation pipeline"
    database: eo_pv_lakehouse  # DuckLake catalog attached in on-run-start
    schema: main  # For dev: tables in main schema, for prod: staging schema
    tables:
      # Consolidated view that unions all individual staging tables
      - name: stg_pv_consolidated
        description: "Consolidated view of all PV datasets with standardized schema (created by Hamilton)"
        columns:
          - name: dataset_name
            description: "Source dataset identifier"
            tests:
              - not_null
          - name: source_file
            description: "Original source file name"
          - name: geometry
            description: "Geometry column (DuckDB spatial type)"
            tests:
              - not_null
          - name: centroid_lon
            description: "Centroid longitude"
            tests:
              - dbt_utils.accepted_range:
                  min_value: -180
                  max_value: 180
          - name: centroid_lat
            description: "Centroid latitude"
            tests:
              - dbt_utils.accepted_range:
                  min_value: -90
                  max_value: 90
          - name: area_m2
            description: "Installation area in square meters"
            tests:
              - dbt_utils.accepted_range:
                  min_value: 0
                  max_value: 1000000
          - name: processed_at
            description: "Hamilton processing timestamp"
            tests:
              - not_null
          - name: unified_id
            description: "Unified identifier across datasets"
          - name: source_area_m2
            description: "Original area from source data"
          - name: capacity_mw
            description: "Capacity in megawatts (if available)"
          - name: install_date
            description: "Installation date (if available)"

      # Individual staging tables (examples - Hamilton creates one per dataset)
      - name: stg_uk_crowdsourced_pv_2020
        description: "Standardized UK Crowdsourced PV 2020 dataset"
        columns:
          - name: dataset_name
            description: "Source dataset identifier"
            tests:
              - not_null
              - accepted_values:
                  values: ['uk_crowdsourced_pv_2020']
          - name: geometry
            description: "Geometry column (DuckDB spatial type)"
            tests:
              - not_null
          - name: area_m2
            description: "Installation area in square meters"
          - name: centroid_lon
            description: "Centroid longitude"
          - name: centroid_lat
            description: "Centroid latitude"
          - name: processed_at
            description: "Hamilton processing timestamp"
            tests:
              - not_null

      - name: stg_chn_med_res_pv_2024
        description: "Standardized China Medium Resolution PV 2024 dataset"
        columns:
          - name: dataset_name
            description: "Source dataset identifier"
            tests:
              - not_null
              - accepted_values:
                  values: ['chn_med_res_pv_2024']
          - name: geometry
            description: "Geometry column (DuckDB spatial type)"
            tests:
              - not_null
          - name: area_m2
            description: "Installation area in square meters"
          - name: centroid_lon
            description: "Centroid longitude"
          - name: centroid_lat
            description: "Centroid latitude"
          - name: processed_at
            description: "Hamilton processing timestamp"
            tests:
              - not_null

      - name: stg_global_pv_inventory_sent2_spot_2021
        description: "Standardized Global PV Inventory Sentinel-2 SPOT 2021 dataset"
        columns:
          - name: dataset_name
            description: "Source dataset identifier"
            tests:
              - not_null
              - accepted_values:
                  values: ['global_pv_inventory_sent2_spot_2021']
          - name: geometry
            description: "Geometry column (DuckDB spatial type)"
            tests:
              - not_null
          - name: area_m2
            description: "Installation area in square meters"
          - name: centroid_lon
            description: "Centroid longitude"
          - name: centroid_lat
            description: "Centroid latitude"
          - name: processed_at
            description: "Hamilton processing timestamp"
            tests:
              - not_null

      - name: stg_ind_pv_solar_farms_2022
        description: "Standardized India PV Solar Farms 2022 dataset"
        columns:
          - name: dataset_name
            description: "Source dataset identifier"
            tests:
              - not_null
              - accepted_values:
                  values: ['ind_pv_solar_farms_2022']
          - name: geometry
            description: "Geometry column (DuckDB spatial type)"
            tests:
              - not_null
          - name: area_m2
            description: "Installation area in square meters"
          - name: centroid_lon
            description: "Centroid longitude"
          - name: centroid_lat
            description: "Centroid latitude"
          - name: processed_at
            description: "Hamilton processing timestamp"
            tests:
              - not_null

      - name: stg_usa_cali_usgs_pv_2016
        description: "Standardized USA California USGS PV 2016 dataset"
        columns:
          - name: dataset_name
            description: "Source dataset identifier"
            tests:
              - not_null
              - accepted_values:
                  values: ['usa_cali_usgs_pv_2016']
          - name: geometry
            description: "Geometry column (DuckDB spatial type)"
            tests:
              - not_null
          - name: area_m2
            description: "Installation area in square meters"
          - name: centroid_lon
            description: "Centroid longitude"
          - name: centroid_lat
            description: "Centroid latitude"
          - name: processed_at
            description: "Hamilton processing timestamp"
            tests:
              - not_null

      - name: stg_global_harmonized_large_solar_farms_2020
        description: "Global Harmonized Large Solar Farms 2020 dataset - Mixed PV types with installation metadata"
        columns:
          - name: dataset_name
            description: "Source dataset identifier"
            tests:
              - not_null
              - accepted_values:
                  values: ['global_harmonized_large_solar_farms_2020']
          - name: geometry
            description: "Geometry column (DuckDB spatial type)"
            tests:
              - not_null
          - name: area_m2
            description: "Installation area in square meters"
          - name: centroid_lon
            description: "Centroid longitude"
          - name: centroid_lat
            description: "Centroid latitude"
          - name: installation_type
            description: "Type of installation (utility, distributed, etc.)"
          - name: installation_date
            description: "Installation date (if available)"
          - name: processed_at
            description: "Hamilton processing timestamp"
            tests:
              - not_null
