# dbt project configuration for EO PV data pipeline
# This file will be used by `dlt dbt generate` to create initial models

name: 'eo_pv_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'eo_pv_pipeline'

# dbt-cloud:
#     project-id: 70471823477636

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  eo_pv_pipeline:
    # Staging models - raw data with geopandas preprocessing (Python models)
    staging:
      +materialized: table
      +schema: staging

    # Prepared models - business logic transformations and data preparation
    prepared:
      +materialized: table
      +schema: prepared

      # Overture Maps models should be views only to minimize storage
      prep_overture_countries:
        +materialized: table
      prep_country_h3_decomposition:
        +materialized: view

      # Large spatial models can use table materialization
      prep_pv_with_admin_boundaries:
        +materialized: table

    # Curated models - final analytical datasets
    curated:
      +materialized: table
      +schema: curated

      # Summary models can be smaller tables
      curated_pv_dataset_summary:
        +materialized: table

# Seed configurations
seeds:
  eo_pv_pipeline:
    +schema: seeds

# Test configurations
tests:
  +store_failures: true
  +schema: test_failures

# Variables for the project
vars:
  # Date range for data processing
  start_date: '2015-01-01'
  end_date: '2024-12-31'

  # Coordinate reference systems
  default_crs: 'EPSG:4326'  # WGS84

  # Data quality thresholds
  min_geometry_area: 10  # minimum area in square meters
  max_geometry_area: 1000000  # maximum area in square meters

  # H3 spatial indexing settings
  h3_resolution: 8  # ~0.7 km² hexagons for PV installations
  h3_country_resolution: 4  # ~1,770 km² hexagons for country decomposition

  # Spatial processing settings
  overlap_threshold: 0.75  # For duplicate detection
  buffer_distance_m: 100   # Buffer for spatial joins

  # DuckDB-specific settings
  use_native_geometry: true  # Use DuckDB spatial extension instead of WKT
  enable_spatial_index: true # Enable spatial indexing for performance


# Note: Sources are properly configured in models/sources.yml
# DuckDB-specific source configurations can be added here if needed

# DuckDB-specific configurations
on-run-start:
  - "INSTALL spatial"
  - "LOAD spatial"
  - "INSTALL ducklake"
  - "LOAD ducklake"
  - "INSTALL h3 FROM community"
  - "LOAD h3"
  # Note: geography extension temporarily commented out due to availability issues
  # - "INSTALL geography FROM community"
  # - "LOAD geography"

  # Attach DuckLake catalog for staging tables (only if not already attached)
  - "ATTACH IF NOT EXISTS 'ducklake:sqlite:{{ env_var('REPO_ROOT') }}/db/ducklake_catalog.sqlite' AS eo_pv_lakehouse (DATA_PATH '{{ env_var('REPO_ROOT') }}/db/ducklake_data/')"
  - "USE eo_pv_lakehouse"
